<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 18-2-1
 * Time: 下午4:15
 */
/*
 * 将一个类的接口适配成用户希望的，类和接口不兼容的问题。下列中可以替换类source来更换合适接口实现类
 */
class classadapter extends classsource implements classinterface{

    public function action()
    {
        // TODO: Implement action() method.
        echo '适配器的类';
    }
}
//对象适配器　通过传入对象来兼容接口　希望转换一个对象
class objectdapter implements classinterface{

    protected $object;
    public function __construct(classsource $object)
    {
        $this->object=$object;
    }

    public function action()
    {
        // TODO: Implement action() method.
    }
    public function method()
    {
        $this->object->method();
        // TODO: Implement method() method.
    }
}
//接口适配器　抽象类实现接口　类继承抽象类，选择性实现方法　　不希望实现接口所有方法
class interfacedaper extends abstractadapter{
    public function method()
    {
        parent::method(); // TODO: Change the autogenerated stub
    }
}